name: ZKP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  zkp:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Protobuf Compiler
      run:  sudo apt-get install protobuf-compiler
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      